Vaadin v1 Добавлена тестовая страница vaadin
IPLATFORM-DS/keycloak-admin-2 pull request #2
Opened 2022-07-14 10:58 UTC by annalana

2022-07-14 13:12 UTC, a-s-eliseev requested changes

2022-07-14 13:12 UTC, a-s-eliseev commented on pom.xml
> +
удалить пустую строку

2022-07-14 13:12 UTC, a-s-eliseev commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/com.vaadin/vaadin-spring-boot-starter -->
почему два комментария?

2022-07-14 13:12 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/repository/UserRepository.java
> +    List<User> findAll();
Такой метод уже есть, попробуй использовать optional

2022-07-16 18:09 UTC, a-s-eliseev approved these changes

2022-07-17 16:42 UTC, youRock19 approved these changes

2022-07-17 17:26 UTC, merged