Ka 39 Описание RealmController
IPLATFORM-DS/keycloak-admin-2 pull request #26
Opened 2022-07-22 19:56 UTC by RalfMog

2022-07-23 15:51 UTC, a-s-eliseev approved these changes

2022-07-23 15:52 UTC, a-s-eliseev requested changes

2022-07-23 15:52 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/dto/RealmDto.java
> +public class RealmDto {
Это, видимо, должно быть в другой ветке

2022-07-24 13:57 UTC, youRock19 approved these changes

2022-07-24 13:57 UTC, youRock19 commented on src/main/java/space/eliseev/keycloakadmin/controller/RealmController.java
> +                    description = "successful operation (may be empty list)")
думаю что array здесь лишний

2022-07-24 13:59 UTC, annalana commented on src/main/java/space/eliseev/keycloakadmin/controller/RealmController.java
> +                    description = "successful operation (may be empty list)")
Здесь есть вариант с 404 статусом, а в описании не вижу

2022-07-24 13:59 UTC, annalana commented on src/main/java/space/eliseev/keycloakadmin/controller/RealmController.java
> +                    description = "successful operation (may be empty list)")
И листа тут по идее нет, поскольку имя уникально. И в контроллере Optional. Поэтому, лучше убрать лист из описания

2022-07-24 17:58 UTC, annalana approved these changes

2022-07-26 15:25 UTC, a-s-eliseev approved these changes

2022-07-26 15:25 UTC, merged