KA-4 Реализован entity Realm
IPLATFORM-DS/keycloak-admin-2 pull request #5
Opened 2022-07-15 13:42 UTC by RalfMog

2022-07-15 14:06 UTC, sotnicoff reviewed
Там где varchar(36) думаю нужно явно указать допустимую длину стринга
Column(name="field_name", length = 36)
И многие поля типа boolean и int имеют начальные значения, думаю нужно присвоить их

2022-07-15 15:51 UTC, sotnicoff approved these changes

2022-07-16 18:07 UTC, a-s-eliseev requested changes

2022-07-16 18:07 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/entity/Role.java
> +public class Role extends BaseEntity {
этого класса быть не должно, из-за него конфликт

2022-07-17 17:25 UTC, a-s-eliseev approved these changes

2022-07-17 17:26 UTC, merged