Rest API для event_entity
IPLATFORM-DS/keycloak-admin-2 pull request #9
Opened 2022-07-16 14:32 UTC by sotnicoff

Не уверен по поводу типа данных для интервала времени.

2022-07-16 18:16 UTC, a-s-eliseev requested changes
Тут еще, видимо, нужно доработать фильтр по дате/времени. Но уже в другой задаче

2022-07-16 18:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/controller/EventController.java
> +        if (events == null) {
это так не работает) сервис может вернуть пустой список

2022-07-16 18:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/controller/EventController.java
> +        if (events == null) {
может быть пустой список

2022-07-16 18:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/controller/EventController.java
> +        if (events == null) {
пустой список

2022-07-16 18:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/repository/EventRepository.java
> +    List<Event> findAllByName(String username);
findAllByUsername

2022-07-16 18:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/repository/EventRepository.java
> +    List<Event> findAllByNameAndTime(String username, Long time);
findAllByUsernameAndTime

2022-07-16 18:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/service/EventService.java
> +    List<Event> getAllByName(String username);
username

2022-07-16 18:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/service/EventService.java
> +    List<Event> getAllByNameAndTime(String username, Long time);
username

2022-07-17 06:57 UTC, sotnicoff commented on src/main/java/space/eliseev/keycloakadmin/controller/EventController.java
> +        if (events == null) {
добавил проверку isEmpty. Не пойму тогда нужна ли в принципе проверка для возврата подходящего статуса? Посмотрел как реализован рест для ролей, который ты утвердил, и там нет никакой проверки, значит мне просто вернуть список типа return new ResponseEntity<>(events, HttpStatus.OK); ?

2022-07-17 09:02 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/controller/EventController.java
> +        if (events == null) {
С событиями все сложнее. Думаю, на следующем созвоне обсудим эту задачу.

2022-07-17 09:03 UTC, a-s-eliseev commented
Задачу отдельно разберем на созвоне.

2022-07-20 10:39 UTC, RalfMog approved these changes

2022-07-30 08:57 UTC, annalana approved these changes

2022-07-30 09:46 UTC, a-s-eliseev approved these changes

2022-07-30 09:46 UTC, merged